-- Migration: Replace full unique constraint on proyectos.codigo with a partial
-- unique index that only enforces uniqueness for non-deleted (active) projects.
-- This allows soft-deleted projects' codes to be reused.

-- 1. Drop the full unique constraint generated by Drizzle's .unique() column modifier
ALTER TABLE "proyectos" DROP CONSTRAINT IF EXISTS "proyectos_codigo_unique";
--> statement-breakpoint

-- 2. Drop the redundant full unique index generated by uniqueIndex() in the table definition
DROP INDEX IF EXISTS "proyectos_codigo_idx";
--> statement-breakpoint

-- 3. Create partial unique index: enforce uniqueness only among active projects
CREATE UNIQUE INDEX "proyectos_codigo_active_idx"
  ON "proyectos" ("codigo")
  WHERE "deleted_at" IS NULL;
