CREATE TYPE IF NOT EXISTS audit_operation AS ENUM ('INSERT', 'UPDATE', 'DELETE');
CREATE TYPE IF NOT EXISTS priority AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'URGENTE');
CREATE TYPE IF NOT EXISTS process_status AS ENUM ('EN_CURSO', 'COMPLETADO', 'CANCELADO', 'PAUSADO');
CREATE TYPE IF NOT EXISTS project_status AS ENUM ('PLANIFICACION', 'ACTIVO', 'PAUSADO', 'COMPLETADO', 'CANCELADO');
CREATE TYPE IF NOT EXISTS responsible_type AS ENUM ('RRHH', 'MANAGER', 'IT', 'EMPLEADO', 'CUSTOM');
CREATE TYPE IF NOT EXISTS task_category AS ENUM ('DOCUMENTACION', 'EQUIPAMIENTO', 'ACCESOS', 'FORMACION', 'REUNIONES', 'ADMINISTRATIVO');
CREATE TYPE IF NOT EXISTS task_status AS ENUM ('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'BLOQUEADA', 'CANCELADA');
CREATE TYPE IF NOT EXISTS time_entry_status AS ENUM ('PENDIENTE', 'APROBADO', 'RECHAZADO');
CREATE TYPE IF NOT EXISTS user_role AS ENUM ('ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO');
