/**
 * Catalogo de casos de uso E2E para TeamHub.
 * Fuente de verdad para extender la suite Playwright por modulo y por rol.
 *
 * Convenciones:
 * - id: E2E-<MODULO>-<NNN>
 * - priority: P0 (critico), P1 (alto), P2 (medio)
 * - type: smoke | regression | negative | security
 */
export type E2ERole = 'ADMIN' | 'RRHH' | 'MANAGER' | 'EMPLEADO' | 'ANON';
export type E2EPriority = 'P0' | 'P1' | 'P2';
export type E2EType = 'smoke' | 'regression' | 'negative' | 'security';

export interface E2EUseCase {
  id: string;
  title: string;
  module: 'auth' | 'navigation' | 'departamentos' | 'usuarios' | 'plantillas' | 'procesos' | 'proyectos' | 'timetracking' | 'perfil' | 'cross-cutting';
  priority: E2EPriority;
  type: E2EType;
  roles: E2ERole[];
  route: string;
  apiContracts: string[];
  businessRules?: string[];
  preconditions: string[];
  expected: string[];
  existingSpec?: string;
}

export const E2E_USE_CASES: E2EUseCase[] = [
  {
    id: 'E2E-AUTH-001',
    title: 'Login UI carga y permite enviar credenciales',
    module: 'auth',
    priority: 'P0',
    type: 'smoke',
    roles: ['ANON'],
    route: '/login',
    apiContracts: ['/auth/login'],
    preconditions: ['Frontend levantado'],
    expected: ['Se renderiza formulario de login', 'Boton iniciar sesion visible'],
    existingSpec: 'frontend/e2e/login.spec.ts',
  },
  {
    id: 'E2E-AUTH-002',
    title: 'Credenciales invalidas muestran error generico',
    module: 'auth',
    priority: 'P0',
    type: 'negative',
    roles: ['ANON'],
    route: '/login',
    apiContracts: ['/auth/login'],
    preconditions: ['Usuario inexistente o password invalido'],
    expected: ['Mensaje generico de error', 'No filtra si el usuario existe'],
    existingSpec: 'frontend/e2e/login.spec.ts',
  },
  {
    id: 'E2E-AUTH-003',
    title: 'Login con MFA completa sesion y redirige a dashboard',
    module: 'auth',
    priority: 'P0',
    type: 'smoke',
    roles: ['ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO'],
    route: '/login',
    apiContracts: ['/auth/login', '/auth/mfa/verify'],
    businessRules: ['auth.mfaTokenTtl=5m', 'auth.totpDigits=6'],
    preconditions: ['Usuario con MFA activo', 'Credenciales en .env.e2e'],
    expected: ['Sesion iniciada', 'Redireccion a /dashboard'],
    existingSpec: 'frontend/e2e/block-a-smoke.spec.ts',
  },
  {
    id: 'E2E-AUTH-004',
    title: 'Cuenta bloqueada tras 3 intentos fallidos',
    module: 'auth',
    priority: 'P1',
    type: 'security',
    roles: ['ANON'],
    route: '/login',
    apiContracts: ['/auth/login'],
    businessRules: ['auth.loginMaxAttempts=3', 'auth.loginLockoutMinutes=30'],
    preconditions: ['Usuario existente', 'Password incorrecta repetida'],
    expected: ['Intento adicional sigue rechazado', 'Mensaje no revela estado interno'],
    existingSpec: 'frontend/e2e/auth.flows.spec.ts',
  },
  {
    id: 'E2E-NAV-001',
    title: 'Ruta raiz redirige segun estado de sesion',
    module: 'navigation',
    priority: 'P0',
    type: 'smoke',
    roles: ['ANON'],
    route: '/',
    apiContracts: [],
    preconditions: ['Sin tokens en localStorage'],
    expected: ['Redireccion a /login'],
    existingSpec: 'frontend/e2e/navigation.spec.ts',
  },
  {
    id: 'E2E-NAV-002',
    title: 'Menu lateral respeta permisos por rol',
    module: 'navigation',
    priority: 'P0',
    type: 'security',
    roles: ['ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO'],
    route: '/dashboard',
    apiContracts: ['/auth/me'],
    preconditions: ['Sesion valida por rol'],
    expected: ['Solo se muestran items permitidos por rol'],
    existingSpec: 'frontend/e2e/block-a-smoke.spec.ts',
  },
  {
    id: 'E2E-DEP-001',
    title: 'Listado de departamentos carga tras login',
    module: 'departamentos',
    priority: 'P0',
    type: 'smoke',
    roles: ['ADMIN', 'RRHH'],
    route: '/admin/departamentos',
    apiContracts: ['/departamentos'],
    preconditions: ['Sesion ADMIN o RRHH'],
    expected: ['Titulo visible', 'Lista cargada o estado vacio'],
    existingSpec: 'frontend/e2e/departamentos-crud.spec.ts',
  },
  {
    id: 'E2E-DEP-002',
    title: 'Crear departamento desde modal',
    module: 'departamentos',
    priority: 'P0',
    type: 'regression',
    roles: ['ADMIN', 'RRHH'],
    route: '/admin/departamentos',
    apiContracts: ['/departamentos'],
    preconditions: ['Sesion ADMIN o RRHH'],
    expected: ['Nuevo departamento visible en listado'],
    existingSpec: 'frontend/e2e/departamentos-crud.spec.ts',
  },
  {
    id: 'E2E-DEP-003',
    title: 'Editar departamento existente',
    module: 'departamentos',
    priority: 'P1',
    type: 'regression',
    roles: ['ADMIN', 'RRHH'],
    route: '/admin/departamentos',
    apiContracts: ['/departamentos/{id}'],
    preconditions: ['Departamento creado previamente'],
    expected: ['Cambios persistidos', 'Tarjeta actualizada'],
    existingSpec: 'frontend/e2e/departamentos.management.spec.ts',
  },
  {
    id: 'E2E-DEP-004',
    title: 'No permite duplicar codigo de departamento',
    module: 'departamentos',
    priority: 'P1',
    type: 'negative',
    roles: ['ADMIN', 'RRHH'],
    route: '/admin/departamentos',
    apiContracts: ['/departamentos'],
    preconditions: ['Existe departamento con codigo objetivo'],
    expected: ['Error de validacion', 'No crea registro duplicado'],
    existingSpec: 'frontend/e2e/departamentos.management.spec.ts',
  },
  {
    id: 'E2E-DEP-005',
    title: 'Soft delete y filtro activo/inactivo',
    module: 'departamentos',
    priority: 'P1',
    type: 'regression',
    roles: ['ADMIN', 'RRHH'],
    route: '/admin/departamentos',
    apiContracts: ['/departamentos/{id}'],
    preconditions: ['Departamento activo existente'],
    expected: ['Delete lo marca inactivo', 'Filtros reflejan estado'],
    existingSpec: 'frontend/e2e/departamentos.management.spec.ts',
  },
  {
    id: 'E2E-DEP-006',
    title: 'Empleado no puede acceder a departamentos admin',
    module: 'departamentos',
    priority: 'P0',
    type: 'security',
    roles: ['EMPLEADO'],
    route: '/admin/departamentos',
    apiContracts: ['/departamentos'],
    preconditions: ['Sesion EMPLEADO'],
    expected: ['Respuesta 403 o redireccion', 'Sin fuga de datos'],
    existingSpec: 'frontend/e2e/block-a-smoke.spec.ts',
  },
  {
    id: 'E2E-USR-001',
    title: 'RRHH crea empleado con departamento',
    module: 'usuarios',
    priority: 'P1',
    type: 'regression',
    roles: ['RRHH', 'ADMIN'],
    route: '/admin/empleados',
    apiContracts: ['/usuarios', '/departamentos'],
    preconditions: ['Sesion RRHH o ADMIN', 'Departamento activo'],
    expected: ['Empleado creado y visible en listado'],
    existingSpec: 'frontend/e2e/usuarios.flows.spec.ts',
  },
  {
    id: 'E2E-USR-002',
    title: 'No permite email duplicado en alta de empleado',
    module: 'usuarios',
    priority: 'P1',
    type: 'negative',
    roles: ['RRHH', 'ADMIN'],
    route: '/admin/empleados',
    apiContracts: ['/usuarios'],
    preconditions: ['Existe usuario con email objetivo'],
    expected: ['Error de duplicado', 'No se crea usuario'],
    existingSpec: 'frontend/e2e/usuarios.flows.spec.ts',
  },
  {
    id: 'E2E-PLA-001',
    title: 'Crear plantilla con tareas',
    module: 'plantillas',
    priority: 'P1',
    type: 'regression',
    roles: ['RRHH', 'ADMIN'],
    route: '/admin/plantillas/crear',
    apiContracts: ['/plantillas', '/plantillas/{id}/tareas'],
    preconditions: ['Sesion RRHH o ADMIN'],
    expected: ['Plantilla creada', 'Detalle muestra tareas'],
  },
  {
    id: 'E2E-PLA-002',
    title: 'Duplicar plantilla desde listado',
    module: 'plantillas',
    priority: 'P1',
    type: 'regression',
    roles: ['RRHH', 'ADMIN'],
    route: '/admin/plantillas',
    apiContracts: ['/plantillas/{id}/duplicar'],
    preconditions: ['Plantilla existente'],
    expected: ['Nueva plantilla clonada con tareas'],
  },
  {
    id: 'E2E-PRO-001',
    title: 'Crear proceso onboarding desde plantilla',
    module: 'procesos',
    priority: 'P1',
    type: 'regression',
    roles: ['RRHH', 'ADMIN', 'MANAGER'],
    route: '/onboarding',
    apiContracts: ['/procesos'],
    preconditions: ['Empleado y plantilla existentes'],
    expected: ['Proceso en estado EN_CURSO con tareas'],
  },
  {
    id: 'E2E-PRO-002',
    title: 'Completar tarea de onboarding como responsable',
    module: 'procesos',
    priority: 'P1',
    type: 'regression',
    roles: ['EMPLEADO', 'MANAGER'],
    route: '/mis-tareas',
    apiContracts: ['/procesos/{id}/tareas/{tareaId}/completar'],
    preconditions: ['Tarea asignada al usuario'],
    expected: ['Tarea pasa a COMPLETADA y fecha se registra'],
  },
  {
    id: 'E2E-PRO-003',
    title: 'Rechazar tarea requiere comentario',
    module: 'procesos',
    priority: 'P1',
    type: 'negative',
    roles: ['MANAGER', 'RRHH', 'ADMIN'],
    route: '/onboarding/{id}',
    apiContracts: ['/procesos/{id}/tareas/{tareaId}/rechazar'],
    preconditions: ['Proceso con tarea pendiente'],
    expected: ['Sin comentario falla', 'Con comentario actualiza estado'],
  },
  {
    id: 'E2E-PRJ-001',
    title: 'Crear proyecto y verlo en listado',
    module: 'proyectos',
    priority: 'P0',
    type: 'regression',
    roles: ['ADMIN', 'RRHH', 'MANAGER'],
    route: '/proyectos/crear',
    apiContracts: ['/proyectos'],
    preconditions: ['Sesion con rol permitido'],
    expected: ['Proyecto visible en /proyectos'],
    existingSpec: 'frontend/e2e/block-a-smoke.spec.ts',
  },
  {
    id: 'E2E-PRJ-002',
    title: 'Gestion de asignaciones: crear y finalizar',
    module: 'proyectos',
    priority: 'P1',
    type: 'regression',
    roles: ['ADMIN', 'RRHH', 'MANAGER'],
    route: '/proyectos/{id}',
    apiContracts: ['/proyectos/{id}/asignaciones', '/proyectos/{id}/asignaciones/{asigId}/finalizar'],
    preconditions: ['Proyecto activo', 'Empleado disponible'],
    expected: ['Asignacion creada', 'Finalizacion actualiza estado'],
  },
  {
    id: 'E2E-PRJ-003',
    title: 'Empleado solo ve sus proyectos en mis-proyectos',
    module: 'proyectos',
    priority: 'P1',
    type: 'security',
    roles: ['EMPLEADO'],
    route: '/proyectos',
    apiContracts: ['/proyectos/mis-proyectos'],
    preconditions: ['Sesion EMPLEADO con y sin asignaciones'],
    expected: ['Solo aparecen proyectos asignados'],
  },
  {
    id: 'E2E-TTR-001',
    title: 'Empleado crea registro de horas pendiente',
    module: 'timetracking',
    priority: 'P0',
    type: 'smoke',
    roles: ['EMPLEADO', 'MANAGER', 'RRHH', 'ADMIN'],
    route: '/timetracking',
    apiContracts: ['/timetracking'],
    preconditions: ['Proyecto asignado al usuario'],
    expected: ['Registro creado con estado PENDIENTE'],
    existingSpec: 'frontend/e2e/block-a-smoke.spec.ts',
  },
  {
    id: 'E2E-TTR-002',
    title: 'No permite crear horas en fecha futura',
    module: 'timetracking',
    priority: 'P1',
    type: 'negative',
    roles: ['EMPLEADO', 'MANAGER', 'RRHH', 'ADMIN'],
    route: '/timetracking',
    apiContracts: ['/timetracking'],
    preconditions: ['Intento de registrar fecha futura'],
    expected: ['Validacion de negocio bloquea el guardado'],
  },
  {
    id: 'E2E-TTR-003',
    title: 'No permite superar limite diario de 14h',
    module: 'timetracking',
    priority: 'P1',
    type: 'negative',
    roles: ['EMPLEADO', 'MANAGER', 'RRHH', 'ADMIN'],
    route: '/timetracking',
    apiContracts: ['/timetracking'],
    preconditions: ['Dia con horas acumuladas cercanas al limite'],
    expected: ['Registro adicional es rechazado'],
  },
  {
    id: 'E2E-TTR-004',
    title: 'Manager aprueba y rechaza registros pendientes',
    module: 'timetracking',
    priority: 'P1',
    type: 'regression',
    roles: ['MANAGER'],
    route: '/timetracking/aprobacion',
    apiContracts: ['/timetracking/pendientes-aprobacion', '/timetracking/{id}/aprobar', '/timetracking/{id}/rechazar'],
    preconditions: ['Existen registros pendientes en su equipo'],
    expected: ['Cambio de estado correcto', 'Rechazo requiere comentario'],
  },
  {
    id: 'E2E-PERF-001',
    title: 'Usuario actualiza datos de perfil',
    module: 'perfil',
    priority: 'P2',
    type: 'regression',
    roles: ['ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO'],
    route: '/perfil',
    apiContracts: ['/perfil'],
    preconditions: ['Sesion valida'],
    expected: ['Cambios persistidos y visibles tras refresco'],
  },
  {
    id: 'E2E-PERF-002',
    title: 'Regenerar backup codes de MFA desde perfil',
    module: 'perfil',
    priority: 'P2',
    type: 'security',
    roles: ['ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO'],
    route: '/perfil',
    apiContracts: ['/perfil/mfa/backup-codes'],
    preconditions: ['MFA habilitado', 'Password actual y TOTP validos'],
    expected: ['Entrega 10 codigos nuevos', 'Codigos anteriores invalidos'],
  },
  {
    id: 'E2E-SEC-001',
    title: 'Token expirado refresca sesion automaticamente',
    module: 'cross-cutting',
    priority: 'P1',
    type: 'security',
    roles: ['ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO'],
    route: '/dashboard',
    apiContracts: ['/auth/refresh'],
    preconditions: ['Access token expirado', 'Refresh token valido'],
    expected: ['Se renueva token sin expulsar al usuario'],
  },
  {
    id: 'E2E-SEC-002',
    title: 'Sin refresh token se limpia sesion y vuelve a login',
    module: 'cross-cutting',
    priority: 'P1',
    type: 'security',
    roles: ['ADMIN', 'RRHH', 'MANAGER', 'EMPLEADO'],
    route: '/dashboard',
    apiContracts: ['/auth/refresh'],
    preconditions: ['Access token expirado', 'Refresh token ausente o invalido'],
    expected: ['Se limpian tokens', 'Redireccion a /login'],
  },
];
